# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitm < Formula
  desc "Git Manager CLI tool"
  homepage "https://github.com/alexDouze/git-manager"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alexDouze/git-manager/releases/download/v0.0.1/gitm_0.0.1_darwin_amd64"
      sha256 "7a27293b3290125fd7b7d28de8b4d2190c7c7bd343987cc15080e603ca5a9804"

      def install
        bin.install "gitm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alexDouze/git-manager/releases/download/v0.0.1/gitm_0.0.1_darwin_arm64"
      sha256 "fbdf50449fbf38d6360a86e246afed2718ca4729ecbd3a6a598990507a33414d"

      def install
        bin.install "gitm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/alexDouze/git-manager/releases/download/v0.0.1/gitm_0.0.1_linux_amd64"
        sha256 "be454be5c9337edcf7550b30920459c72026141eb03d69544222bddca887a847"

        def install
          bin.install "gitm"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/alexDouze/git-manager/releases/download/v0.0.1/gitm_0.0.1_linux_arm64"
        sha256 "b67c47983390e9357ae37de97254403d6b11bb59fd86ca8dd708e464c239bfe1"

        def install
          bin.install "gitm"
        end
      end
    end
  end

  test do
    system "#{bin}/gitm", "version"
  end
end
