# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitm < Formula
  desc "Git Manager CLI tool"
  homepage "https://github.com/alexDouze/git-manager"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alexDouze/git-manager/releases/download/v0.0.3/gitm_0.0.3_darwin_amd64"
      sha256 "fc4001956bd251d7e806b82551aa6027255dad56f2592a4b47e0a44254cc9d5d"

      def install
        bin.install "gitm_0.0.3_darwin_amd64" => "gitm"
        generate_completions_from_executable(bin/"gitm", "completions")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alexDouze/git-manager/releases/download/v0.0.3/gitm_0.0.3_darwin_arm64"
      sha256 "fd65d5ea863bbc2278f024ac47029745c3922d2b18477eae6c19897b95379cb4"

      def install
        bin.install "gitm_0.0.3_darwin_arm64" => "gitm"
        generate_completions_from_executable(bin/"gitm", "completions")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/alexDouze/git-manager/releases/download/v0.0.3/gitm_0.0.3_linux_amd64"
        sha256 "630bf87816a1a882b74080873d47eadd49a1372d4563e7b0994d5872b3b52de1"

        def install
          bin.install "gitm_0.0.3_linux_amd64" => "gitm"
          generate_completions_from_executable(bin/"gitm", "completions")
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/alexDouze/git-manager/releases/download/v0.0.3/gitm_0.0.3_linux_arm64"
        sha256 "1b5b61ec0425f629e9bb3d40a1b787cc9b76084bcfde05a61ca5eb4bcd84ac72"

        def install
          bin.install "gitm_0.0.3_linux_arm64" => "gitm"
          generate_completions_from_executable(bin/"gitm", "completions")
        end
      end
    end
  end

  test do
    system "#{bin}/gitm", "version"
  end
end
