# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitm < Formula
  desc "Git Manager CLI tool"
  homepage "https://github.com/alexDouze/git-manager"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alexDouze/git-manager/releases/download/v0.0.1/gitm_0.0.1_darwin_amd64"
      sha256 "f90e8465690d31563710ed86fbac895191976f619ce9d89933fef2b9b5d61051"

      def install
        bin.install "gitm_0.0.1_darwin_amd64" => "gitm"
        chmod 0555, bin/"gitm"
        generate_completions_from_executable(bin/"gitm", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alexDouze/git-manager/releases/download/v0.0.1/gitm_0.0.1_darwin_arm64"
      sha256 "2124cc98a9357113ecee68e00ea2b79b29ce5d362dde96af964d0428fb0c200d"

      def install
        bin.install "gitm_0.0.1_darwin_arm64" => "gitm"
        chmod 0555, bin/"gitm"
        generate_completions_from_executable(bin/"gitm", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/alexDouze/git-manager/releases/download/v0.0.1/gitm_0.0.1_linux_amd64"
        sha256 "78ff54effee23773281aa52a2852df92e57760950cdf9dc962d35a6116f96677"

        def install
          bin.install "gitm_0.0.1_linux_amd64" => "gitm"
          chmod 0555, bin/"gitm"
          generate_completions_from_executable(bin/"gitm", "completion")
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/alexDouze/git-manager/releases/download/v0.0.1/gitm_0.0.1_linux_arm64"
        sha256 "065f4b60930f1667c4b6b62940ae7d12391520ca29ae4f2f05034ab6131f52fb"

        def install
          bin.install "gitm_0.0.1_linux_arm64" => "gitm"
          chmod 0555, bin/"gitm"
          generate_completions_from_executable(bin/"gitm", "completion")
        end
      end
    end
  end

  test do
    system "#{bin}/gitm", "version"
  end
end
