# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class K3kcli < Formula
  desc "The k3kcli provides a quick and easy way to create K3k clusters and automatically exposes them via a kubeconfig."
  homepage "https://github.com/rancher/k3k"
  version "0.3.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rancher/k3k/releases/download/v0.3.0/k3kcli-darwin-amd64"
      sha256 "c0546eddf6d5ce3eceae3784c453411496c8c655642a2718cd4b92850003e54a"

      def install
        bin.install "k3kcli-darwin-amd64" => "k3kcli"
        chmod 0555, bin/"k3kcli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rancher/k3k/releases/download/v0.3.0/k3kcli-darwin-arm64"
      sha256 "42790e65fb9a286e7564d80f95b1f2e17641fc23024f3a72c02efda7ec369de8"

      def install
        bin.install "k3kcli-darwin-arm64" => "k3kcli"
        chmod 0555, bin/"k3kcli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rancher/k3k/releases/download/v0.3.0/k3kcli-linux-amd64"
        sha256 "22d5607c98b1ce080b5570f6ad6cf62fa211fbd6cfa15e4dc788a3335784a1f3"

        def install
          bin.install "k3kcli-linux-amd64" => "k3kcli"
          chmod 0555, bin/"k3kcli"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rancher/k3k/releases/download/v0.3.0/k3kcli-linux-arm64"
        sha256 "6e562cd0ec6ca51aa0cf35a5280c9387ba9ca4fb522f6737e547b22505f4e5e0"

        def install
          bin.install "k3kcli-linux-arm64" => "k3kcli"
          chmod 0555, bin/"k3kcli"
        end
      end
    end
  end

  test do
    system "#{bin}/k3kcli", "--version"
  end
end
